language: generic

addons:
  snaps:
    - name: snapcraft
      channel: stable
      confinement: classic
    - name: lxd
      channel: stable
script: sudo snapcraft --use-lxd
deploy:
  provider: snap
  edge: true
